-- ===========================================
--  CUPANG NHS CONCERN MANAGEMENT SYSTEM
--  Legacy reference schema (DO NOT run manually)
--
--  Schema is now managed by Knex.js migrations.
--  See: server/migrations/
--
--  To apply migrations:  npm run migrate:latest
--  To rollback:          npm run migrate:rollback
--  To create new:        npm run migrate:make <name>
--  To seed data:         npm run seed:run
-- ===========================================
